@base = http://localhost:8000
# @base = https://time-trace-api.systemnear.com
@SN_AUTH_API_API_KEY = u4vt5araj8onqptdnlcdlcteg7deumgbae2j3rq548ldrd1eju4c5vkj8nhs
@SN_AUTH_API_COMPANY_API_KEY = 0f050b5a1d191f0008190a081c020b06540f5801550a5e0f091e02025e0c
@SN_AUTH_API_COMPANY_ID = 4fke6e1rht8jqv89dc2jrk704u22lv

### User Register 2FA Init
POST {{base}}/api/v1/user/two-factor-auth/init
content-Type: application/json
x-sn-auth-api-key: {{SN_AUTH_API_API_KEY}}
x-company-api-key: {{SN_AUTH_API_COMPANY_API_KEY}}

{
	"email": "felipe.t.iwamoto@gmail.com",
	"tokenContext": "REGISTER"
}
### User Register 2FA Verification
POST {{base}}/api/v1/user/two-factor-auth/verification
content-Type: application/json
x-company-api-key: {{SN_AUTH_API_COMPANY_API_KEY}}

{
	"email": "felipe.t.iwamoto@gmail.com",
	"token": "nd8dnt",
	"tokenContext": "REGISTER"
}

### User Register
POST {{base}}/api/v1/user/register
content-Type: application/json
x-company-api-key: {{SN_AUTH_API_COMPANY_API_KEY}}

{
	"name": "System Near",
	"email": "felipe.t.iwamoto@gmail.com",
	"password": "Iop890@@",
	"confirmPassword": "Iop890@@"
}
