@base = http://localhost:8000
@USER_AUTH_ID = 9msn7g24qpkvagda0ehb1clfnjoefd
@TIME_TRACE_API_KEY = gcivd2h5m5k4i7ct5ucrr4q0ucv8h496bpl5jlisstejalkis8876ru22cca
### User Product Tag Delete
DELETE {{base}}/api/v1/user/product-tag/delete
content-Type: application/json
x-user-auth-id: {{USER_AUTH_ID}}
x-time-trace-api-key: {{TIME_TRACE_API_KEY}}

{
	"ids": ["cfnceu57ksos60j81o109glh8hkn3t", "enomj6vb08sbp97gil734g7ng6l4o1"]
}
