@base = http://localhost:8000
@USER_AUTH_ID = 9msn7g24qpkvagda0ehb1clfnjoefd
@TIME_TRACE_API_KEY = gcivd2h5m5k4i7ct5ucrr4q0ucv8h496bpl5jlisstejalkis8876ru22cca

### User Product Category Delete
DELETE {{base}}/api/v1/user/product-category/delete
content-Type: application/json
x-user-auth-id: {{USER_AUTH_ID}}
x-time-trace-api-key: {{TIME_TRACE_API_KEY}}

{
	"ids": ["1ccc30equ0ka3h7l9rgt60sp2dechc", "jnh6jpdic2s94lj31o4tpgvmndckmf"]
}
